swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10030
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /status:
    x-swagger-router-controller: status
    get:
      description: Returns server status to the caller
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /supply:
    x-swagger-router-controller: supply
    post:
      description: Begin supply of the products
      operationId: supply
      parameters:
        - name: supply
          in: body
          description: Supply information
          required: true
          schema:
            type: object
            properties:
              trxID:
                type: string
              orderID:
                type: string
              amount:
                type: number
              cart:
                type: array
                items:
                  type: object
                  properties:
                    slug:
                      type: string
                    quantity:
                      type: integer
                    color:
                      type: string
                    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /confirm:
    x-swagger-router-controller: supply
    post:
      description: Begin supply of the products
      operationId: confirm
      parameters:
        - name: order
          in: body
          description: Supply information
          required: true
          schema:
            type: object
            properties:
              orderID:
                type: string
                    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /supplies:
    x-swagger-router-controller: supply
    get:
      description: Get all supply orders
      operationId: supplies
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuppliesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuppliesResponse:
    required:
      - message
    properties:
      message:
        type: object
        properties:
          orderID:
            type: string
          trxID:
            type: string
          amount:
            type: number
          status:
            type: string
          cart:
            type: array
            items:
              type: object
              properties:
                quantity:
                  type: number
                color:
                  type: string
                price:
                  type: number
                name:
                  type: string
                image:
                  type: string
                index:
                  type: number
                id: 
                  type: string
                size:
                  type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
