swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10030
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /status:
    x-swagger-router-controller: status
    get:
      description: Returns server status to the caller
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /supply:
    x-swagger-router-controller: supply
    post:
      description: Begin supply of the products
      operationId: supply
      parameters:
        - name: supply
          in: body
          description: Supply information
          required: true
          schema:
            type: object
            properties:
              trxID:
                type: string
              cart:
                type: array
                items:
                  type: object
                  properties:
                    slug:
                      type: string
                    quantity:
                      type: integer
                    color:
                      type: string
                    
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
