swagger: "2.0"
info:
  version: "0.0.1"
  title: Bank App
# during dev, should point to your local machine
host: localhost:10020
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /status:
    x-swagger-router-controller: status
    get:
      description: Returns server status to the caller
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /connect:
    x-swagger-router-controller: connect
    post:
      description: connect bank with e-commerce
      operationId: connect
      parameters:
        - name: user
          in: body
          description: User information for connection
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              uuid:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VerificationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /verify:
    x-swagger-router-controller: verify
    post:
      description: Verification endpoint
      operationId: verify
      parameters:
        - name: user
          in: body
          description: User information for verification
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VerificationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /validate:
    x-swagger-router-controller: verify
    post:
      description: Verification endpoint
      operationId: validate
      parameters:
        - name: user
          in: body
          description: User information for verification
          required: true
          schema:
            type: object
            properties:
              trxID:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VerificationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /payment:
    x-swagger-router-controller: payment
    post:
      description: Confirm payment
      operationId: payment
      parameters:
        - name: user
          in: body
          description: User information for verification
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              amount:
                type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PaymentResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /balance:
    x-swagger-router-controller: payment
    post:
      description: Get balance
      operationId: balance
      parameters:
        - name: user
          in: body
          description: User information for verification
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BalanceResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /supplyPayment:
    x-swagger-router-controller: payment
    post:
      description: Get balance
      operationId: supplyPayment
      parameters:
        - name: user
          in: body
          description: User information for verification
          required: true
          schema:
            type: object
            properties:
              amount:
                type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BalanceResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /signin:
    x-swagger-router-controller: authentication_controller
    post:
      description: Sign in endpoint
      operationId: signin
      parameters:
        - name: user
          in: body
          description: User information for sign in
          required: true
          schema:
            type: object
            properties:
              uuid:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LoginResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  VerificationResponse:
    required:
      - message
    properties:
      message:
        type: boolean
  BalanceResponse:
    required:
      - message
    properties:
      message:
        type: number
  PaymentResponse:
    required:
      - message
    properties:
      message:
        type: string
  LoginResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
